spring:
  application:
    name: ms-people

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

format:
  password: '[A-Za-z0-9]+'